from __future__ import annotations

import json
import os
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import Any

from .errors import error_response

WORKSPACE_META_DIR = ".cst_runtime"
WORKSPACE_META_FILE = "workspace.json"
WORKSPACE_SCHEMA_VERSION = 1


def now_iso() -> str:
    return datetime.now().astimezone().isoformat(timespec="seconds")


def skill_root() -> Path:
    return Path(__file__).resolve().parents[3]


def scripts_root() -> Path:
    return Path(__file__).resolve().parents[2]


def marker_path(workspace_root: Path) -> Path:
    return workspace_root / WORKSPACE_META_DIR / WORKSPACE_META_FILE


def find_workspace_marker(start: Path | None = None) -> Path | None:
    current = (start or Path.cwd()).expanduser().resolve()
    if current.is_file():
        current = current.parent
    for candidate in (current, *current.parents):
        marker = marker_path(candidate)
        if marker.exists() and marker.is_file():
            return marker
    return None


def resolve_workspace_root(explicit_workspace: str = "") -> tuple[Path, str, bool]:
    if explicit_workspace:
        root = Path(explicit_workspace).expanduser().resolve()
        return root, "argument", marker_path(root).exists()

    env_workspace = os.environ.get("CST_WORKSPACE", "").strip()
    if env_workspace:
        root = Path(env_workspace).expanduser().resolve()
        return root, "CST_WORKSPACE", marker_path(root).exists()

    marker = find_workspace_marker()
    if marker:
        return marker.parents[1], "ancestor_marker", True

    return Path.cwd().resolve(), "cwd", False


def workspace_status(explicit_workspace: str = "") -> dict[str, Any]:
    root, source, initialized = resolve_workspace_root(explicit_workspace)
    marker = marker_path(root)
    expected_dirs = ["tasks", "refs", "docs"]
    return {
        "workspace_root": root.as_posix(),
        "workspace_source": source,
        "workspace_initialized": initialized,
        "workspace_marker": marker.as_posix(),
        "expected_dirs": {
            name: (root / name).exists() and (root / name).is_dir()
            for name in expected_dirs
        },
    }


def _create_pyproject_template(root: Path) -> str | None:
    """Create a minimal pyproject.toml if one does not already exist."""
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        return None
    content = (
        '[project]\n'
        'name = "cst-runtime-workspace"\n'
        'version = "0.1.0"\n'
        'description = "CST runtime workspace - auto-generated by init-workspace"\n'
        'requires-python = ">=3.12"\n'
        'dependencies = []\n'
        '\n'
        '[tool.uv.sources]\n'
        '# cst-studio-suite-link will be configured by install-cst-libraries\n'
    )
    pyproject.write_text(content, encoding="utf-8")
    return pyproject.as_posix()


def _ensure_scripts_pyproject() -> str | None:
    """Create scripts/pyproject.toml if it does not exist."""
    pyproject = scripts_root() / "pyproject.toml"
    if pyproject.exists():
        return None
    content = (
        '[project]\n'
        'name = "cst-runtime"\n'
        'version = "0.1.0"\n'
        'description = "CST Runtime CLI - production entry point"\n'
        'requires-python = ">=3.12"\n'
        '\n'
        '[project.scripts]\n'
        'cst-runtime = "cst_runtime.cli:main"\n'
    )
    pyproject.write_text(content, encoding="utf-8")
    return pyproject.as_posix()


def init_workspace(workspace: str = "") -> dict[str, Any]:
    try:
        root, source, already_initialized = resolve_workspace_root(workspace)
        root.mkdir(parents=True, exist_ok=True)
        for dirname in ("tasks", "refs", "docs"):
            (root / dirname).mkdir(parents=True, exist_ok=True)

        meta_dir = root / WORKSPACE_META_DIR
        meta_dir.mkdir(parents=True, exist_ok=True)
        meta_file = meta_dir / WORKSPACE_META_FILE
        existing: dict[str, Any] = {}
        if meta_file.exists():
            try:
                existing = json.loads(meta_file.read_text(encoding="utf-8-sig"))
            except Exception:
                existing = {}

        created_at = existing.get("created_at") or now_iso()
        payload = {
            "schema_version": WORKSPACE_SCHEMA_VERSION,
            "workspace_type": "cst_runtime_skill_workspace",
            "created_at": created_at,
            "updated_at": now_iso(),
            "skill_root_at_init": skill_root().as_posix(),
            "notes": [
                "This is a minimal CST runtime workspace.",
                "It is not a full CST Studio Suite project repository.",
                "Production runs still require an explicit source_project .cst/.prj file.",
            ],
        }
        meta_file.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

        pyproject_created = _create_pyproject_template(root)
        scripts_pyproject_created = _ensure_scripts_pyproject()

        created = [(root / name).as_posix() for name in ("tasks", "refs", "docs")]
        if pyproject_created:
            created.append(pyproject_created)
        if scripts_pyproject_created:
            created.append(scripts_pyproject_created)

        return {
            "status": "success",
            "workspace_root": root.as_posix(),
            "workspace_source": source,
            "already_initialized": already_initialized,
            "workspace_marker": meta_file.as_posix(),
            "created_dirs": created,
            "pyproject_created": pyproject_created,
            "runtime_module": "cst_runtime.core.workspace",
        }
    except Exception as exc:
        return error_response("init_workspace_failed", str(exc), runtime_module="cst_runtime.core.workspace")


def _project_companion(path: Path) -> Path | None:
    if path.suffix.lower() == ".prj":
        comp = path.parent
    elif path.suffix.lower() == ".cst":
        comp = path.with_suffix("")
    else:
        return None
    return comp if comp.is_dir() else None


def _copy_project(src: Path, dst: Path) -> None:
    shutil.copy2(src, dst)
    comp = _project_companion(src)
    if comp:
        shutil.copytree(comp, dst.with_suffix(""), dirs_exist_ok=True)


def _move_project(src: Path, dst: Path) -> None:
    shutil.move(str(src), str(dst))
    comp = _project_companion(src)
    if comp:
        shutil.move(str(comp), str(dst.with_suffix("")))


def safe_task_id(task_id: str) -> str:
    value = task_id.strip()
    if not value:
        raise ValueError("task_id is required")
    allowed = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-")
    if any(char not in allowed for char in value):
        raise ValueError("task_id may only contain letters, numbers, underscore, and hyphen")
    return value


def init_task(
    *,
    workspace: str = "",
    task_id: str,
    source_project: str,
    goal: str = "",
    title: str = "",
    force: bool = False,
) -> dict[str, Any]:
    try:
        workspace_result = init_workspace(workspace)
        if workspace_result.get("status") == "error":
            return workspace_result
        root = Path(str(workspace_result["workspace_root"]))
        resolved_task_id = safe_task_id(task_id)
        task_dir = root / "tasks" / resolved_task_id
        runs_dir = task_dir / "runs"
        task_json = task_dir / "task.json"
        if task_json.exists() and not force:
            return error_response(
                "task_already_exists",
                "task.json already exists; pass --force true or force=true to overwrite",
                task_path=task_dir.as_posix(),
                runtime_module="cst_runtime.core.workspace",
            )
        task_dir.mkdir(parents=True, exist_ok=True)
        runs_dir.mkdir(parents=True, exist_ok=True)

        # Import source project into refs/ if outside refs/
        refs_root = root / "refs"
        sp_import_msg = ""
        if source_project.strip():
            sp_path = Path(source_project).expanduser().resolve()
            if sp_path.exists() and refs_root.resolve() not in sp_path.parents:
                ref_target = refs_root / sp_path.name
                ref_target.parent.mkdir(parents=True, exist_ok=True)
                in_workspace_root = sp_path.parent == root.resolve()
                if in_workspace_root:
                    _move_project(sp_path, ref_target)
                    sp_import_msg = f"已将源文件从工作区根目录移至 {ref_target.as_posix()}"
                else:
                    _copy_project(sp_path, ref_target)
                    sp_import_msg = f"已从外部路径复制源文件至 {ref_target.as_posix()}"
                source_project = ref_target.as_posix()

        payload = {
            "task_id": resolved_task_id,
            "title": title or goal or resolved_task_id,
            "goal": goal,
            "source_project": source_project,
            "created_at": now_iso(),
            "status": "initialized",
            "workspace_root": root.as_posix(),
        }
        task_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return {
            "status": "success",
            "workspace_root": root.as_posix(),
            "task_id": resolved_task_id,
            "task_path": task_dir.as_posix(),
            "task_json": task_json.as_posix(),
            "runs_dir": runs_dir.as_posix(),
            "source_project": source_project,
            "source_project_exists": Path(source_project).expanduser().exists() if source_project else False,
            "source_import_message": sp_import_msg or None,
            "runtime_module": "cst_runtime.core.workspace",
        }
    except Exception as exc:
        return error_response("init_task_failed", str(exc), runtime_module="cst_runtime.core.workspace")


def load_json_file(file_path: Path) -> dict[str, Any]:
    if not file_path.exists():
        return {}
    return json.loads(file_path.read_text(encoding="utf-8-sig"))


def write_json_file(file_path: Path, payload: dict[str, Any]) -> None:
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def find_next_run_index(runs_dir: Path) -> int:
    max_run_index = 0
    if runs_dir.exists():
        for child in runs_dir.iterdir():
            if not child.is_dir():
                continue
            match = re.fullmatch(r"run_(\d+)", child.name)
            if match:
                max_run_index = max(max_run_index, int(match.group(1)))
    return max_run_index + 1


def render_initial_summary(
    *,
    task_id: str,
    run_id: str,
    created_at: str,
    goal: str,
    target_metric: str,
    objective: str,
    frequency_start_ghz: float | None,
    frequency_end_ghz: float | None,
    source_project: Path,
    working_project: Path,
) -> str:
    lines = [
        f"# {run_id} Summary",
        "",
        "## Run Info",
        f"- run_id: {run_id}",
        f"- task_id: {task_id}",
        f"- created_at: {created_at}",
        f"- source_project: `{source_project.as_posix()}`",
        f"- working_project: `{working_project.as_posix()}`",
        "",
        "## Goal",
        goal or "TBD",
        "",
        "## Target Metrics",
        f"- primary: {target_metric or 'TBD'}",
        f"- objective: {objective or 'TBD'}",
    ]
    if frequency_start_ghz is not None or frequency_end_ghz is not None:
        lines.extend(
            [
                "",
                "## Frequency Range",
                f"- start_ghz: {frequency_start_ghz if frequency_start_ghz is not None else 'TBD'}",
                f"- end_ghz: {frequency_end_ghz if frequency_end_ghz is not None else 'TBD'}",
            ]
        )
    lines.extend(
        [
            "",
            "## Status",
            "- status: prepared",
            "- next_step: open `projects/working.cst` and continue the simulation workflow",
            "",
            "## Notes",
            "- This run is created from a read-only source project copy.",
            "- Exported artifacts should be written into `exports/`.",
        ]
    )
    return "\n".join(lines) + "\n"


def copy_project_artifacts(source_project: Path, working_project: Path) -> Path | None:
    if source_project.suffix.lower() == ".prj":
        source_companion = source_project.parent
    else:
        source_companion = source_project.with_suffix("")

    working_project.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_project, working_project)

    if not source_companion.exists() or not source_companion.is_dir():
        return None

    lock_files = list(source_companion.rglob("*.lok"))
    if lock_files:
        raise RuntimeError("source project appears to be locked; close the CST project before copying")

    working_companion = working_project.with_suffix("")
    shutil.copytree(
        source_companion,
        working_companion,
        ignore=shutil.ignore_patterns("*.lok", "*.tmp"),
    )
    return working_companion


def resolve_run_dir(task_path: str, run_id: str = "") -> tuple[Path, str, Path]:
    task_dir = Path(task_path).expanduser().resolve()
    if not task_dir.exists() or not task_dir.is_dir():
        raise FileNotFoundError(f"task_path 涓嶅瓨鍦ㄦ垨涓嶆槸鐩綍: {task_path}")

    resolved_run_id = (run_id or "").strip()
    if not resolved_run_id:
        latest_path = task_dir / "latest"
        if not latest_path.exists():
            raise FileNotFoundError(f"鏈彁渚?run_id锛屼笖鏈壘鍒?latest 鏂囦欢: {latest_path}")
        resolved_run_id = latest_path.read_text(encoding="utf-8-sig").strip()
    resolved_run_id = resolved_run_id.lstrip("\ufeff")

    if not re.fullmatch(r"run_\d+", resolved_run_id):
        raise ValueError(f"run_id 鏍煎紡閿欒锛屽簲涓?run_xxx: {resolved_run_id}")

    run_dir = task_dir / "runs" / resolved_run_id
    if not run_dir.exists() or not run_dir.is_dir():
        raise FileNotFoundError(f"run 鐩綍涓嶅瓨鍦? {run_dir}")
    return task_dir, resolved_run_id, run_dir


def prepare_new_run(
    task_path: str,
    source_project: str = "",
    goal: str = "",
    target_metric: str = "",
    objective: str = "",
    frequency_start_ghz: float | None = None,
    frequency_end_ghz: float | None = None,
    allow_interactive: bool = True,
    save_project_after_simulation: bool = True,
) -> dict[str, Any]:
    try:
        task_dir = Path(task_path).expanduser().resolve()
        if not task_dir.exists() or not task_dir.is_dir():
            return error_response("task_path_missing", f"task_path 涓嶅瓨鍦ㄦ垨涓嶆槸鐩綍: {task_path}")

        task_json_path = task_dir / "task.json"
        task_data = load_json_file(task_json_path)
        task_id = task_data.get("task_id") or task_dir.name
        resolved_goal = goal or task_data.get("goal") or task_data.get("title") or ""

        resolved_source_project = source_project or task_data.get("source_project") or ""
        if not resolved_source_project:
            return error_response(
                "source_project_missing",
                "鏈彁渚?source_project锛屼笖 task.json 涓湭鎵惧埌 source_project",
            )

        source_project_path = Path(resolved_source_project).expanduser().resolve()
        if source_project_path.is_dir():
            prj_files = [f for f in source_project_path.iterdir() if f.suffix.lower() == ".prj"]
            if prj_files:
                source_project_path = prj_files[0]
            else:
                return error_response(
                    "source_project_missing",
                    f"source_project 鐩綍涓病鏈夋壘鍒?.prj 鏂囦欢: {source_project_path.as_posix()}",
                    source_project=source_project_path.as_posix(),
                )
        elif source_project_path.suffix.lower() != ".cst" and source_project_path.suffix.lower() != ".prj":
            cst_path = source_project_path.with_suffix(".cst")
            prj_path = source_project_path.with_suffix(".prj")
            if cst_path.exists() and cst_path.is_file():
                source_project_path = cst_path
            elif prj_path.exists() and prj_path.is_file():
                source_project_path = prj_path
            else:
                return error_response(
                    "source_project_missing",
                    f"source_project 涓嶅瓨鍦? {source_project_path.as_posix()}",
                    source_project=source_project_path.as_posix(),
                )
        if not source_project_path.exists() or not source_project_path.is_file():
            return error_response(
                "source_project_missing",
                f"source_project 涓嶅瓨鍦? {source_project_path.as_posix()}",
                source_project=source_project_path.as_posix(),
            )

        runs_dir = task_dir / "runs"
        run_index = find_next_run_index(runs_dir)
        run_id = f"run_{run_index:03d}"
        run_dir = runs_dir / run_id
        projects_dir = run_dir / "projects"
        exports_dir = run_dir / "exports"
        logs_dir = run_dir / "logs"
        stages_dir = run_dir / "stages"
        analysis_dir = run_dir / "analysis"

        for path in [runs_dir, run_dir, projects_dir, exports_dir, logs_dir, stages_dir, analysis_dir]:
            path.mkdir(parents=True, exist_ok=True)

        working_project = projects_dir / "working.cst"
        working_companion = copy_project_artifacts(source_project_path, working_project)
        created_at = now_iso()

        config_payload = {
            "task_id": task_id,
            "run_id": run_id,
            "source_project": source_project_path.as_posix(),
            "working_project": working_project.resolve().as_posix(),
            "goal": resolved_goal,
            "target_metrics": {
                "primary": target_metric,
                "objective": objective,
            },
            "frequency_range": {
                "start_ghz": frequency_start_ghz,
                "end_ghz": frequency_end_ghz,
            },
            "allow_interactive": allow_interactive,
            "save_project_after_simulation": save_project_after_simulation,
            "created_at": created_at,
        }
        status_payload = {
            "task_id": task_id,
            "run_id": run_id,
            "status": "prepared",
            "stage": "workspace_prepared",
            "started_at": created_at,
            "completed_at": None,
            "best_result": None,
            "output_files": {},
            "error": None,
        }
        stage_payload = {
            "task_id": task_id,
            "run_id": run_id,
            "stage": "stage_00_workspace_prepared",
            "status": "prepared",
            "created_at": created_at,
            "source_project": source_project_path.as_posix(),
            "working_project": working_project.resolve().as_posix(),
            "working_project_dir": (working_companion.resolve().as_posix() if working_companion else working_project.with_suffix("").resolve().as_posix()),
        }

        config_path = run_dir / "config.json"
        status_path = run_dir / "status.json"
        summary_path = run_dir / "summary.md"
        stage_path = stages_dir / "stage_00_workspace_prepared.json"
        log_path = logs_dir / "run_init.log"
        latest_path = task_dir / "latest"

        write_json_file(config_path, config_payload)
        write_json_file(status_path, status_payload)
        write_json_file(stage_path, stage_payload)
        summary_path.write_text(
            render_initial_summary(
                task_id=task_id,
                run_id=run_id,
                created_at=created_at,
                goal=resolved_goal,
                target_metric=target_metric,
                objective=objective,
                frequency_start_ghz=frequency_start_ghz,
                frequency_end_ghz=frequency_end_ghz,
                source_project=source_project_path,
                working_project=working_project.resolve(),
            ),
            encoding="utf-8",
        )
        log_path.write_text(
            (
                f"[{created_at}] prepared new run workspace\n"
                f"task_id={task_id}\n"
                f"run_id={run_id}\n"
                f"source_project={source_project_path.as_posix()}\n"
                f"working_project={working_project.resolve().as_posix()}\n"
            ),
            encoding="utf-8",
        )
        latest_path.write_text(run_id, encoding="utf-8")

        return {
            "status": "success",
            "task_id": task_id,
            "run_id": run_id,
            "run_dir": run_dir.resolve().as_posix(),
            "working_project": working_project.resolve().as_posix(),
            "working_project_dir": (working_companion.resolve().as_posix() if working_companion else working_project.with_suffix("").resolve().as_posix()),
            "config_path": config_path.resolve().as_posix(),
            "status_path": status_path.resolve().as_posix(),
            "summary_path": summary_path.resolve().as_posix(),
            "latest_path": latest_path.resolve().as_posix(),
            "runtime_module": "cst_runtime.core.workspace",
            "message": f"Created {run_id} with project copy and initial docs.",
        }
    except Exception as exc:
        return error_response("prepare_new_run_failed", f"prepare_new_run 澶辫触: {str(exc)}")


def get_run_context(task_path: str, run_id: str = "") -> dict[str, Any]:
    try:
        task_dir, resolved_run_id, run_dir = resolve_run_dir(task_path, run_id)
        config_path = run_dir / "config.json"
        status_path = run_dir / "status.json"
        working_project = run_dir / "projects" / "working.cst"
        return {
            "status": "success",
            "task_path": task_dir.as_posix(),
            "run_id": resolved_run_id,
            "run_dir": run_dir.as_posix(),
            "working_project": working_project.as_posix(),
            "projects_dir": (run_dir / "projects").as_posix(),
            "exports_dir": (run_dir / "exports").as_posix(),
            "logs_dir": (run_dir / "logs").as_posix(),
            "stages_dir": (run_dir / "stages").as_posix(),
            "analysis_dir": (run_dir / "analysis").as_posix(),
            "config_path": config_path.as_posix(),
            "status_path": status_path.as_posix(),
            "summary_path": (run_dir / "summary.md").as_posix(),
            "config": load_json_file(config_path),
            "run_status": load_json_file(status_path),
            "runtime_module": "cst_runtime.core.workspace",
        }
    except Exception as exc:
        return error_response("get_run_context_failed", f"get_run_context 澶辫触: {str(exc)}")

