function defineMaterial(mws,name,epsr,mur,tand,tandfreq,transparent)
%DEFINEMATERIAL 新建一个材料
%
sComment = sprintf([...
    'With Material\n', ...
    '.Reset\n', ...
    '.Name "%s"\n', ...              % 在这里插入 name 变量
    '.Folder ""\n', ...
    '.Rho "0.0"\n', ...
    '.ThermalType "Normal"\n', ...
    '.ThermalConductivity "0"\n', ...
    '.SpecificHeat "0", "J/K/kg"\n', ...
    '.DynamicViscosity "0"\n', ...
    '.Emissivity "0"\n', ...
    '.MetabolicRate "0.0"\n', ...
    '.VoxelConvection "0.0"\n', ...
    '.BloodFlow "0"\n', ...
    '.MechanicsType "Unused"\n', ...
    '.IntrinsicCarrierDensity "0"\n', ...
    '.FrqType "all"\n', ...
    '.Type "Normal"\n', ...
    '.MaterialUnit "Frequency", "GHz"\n', ...
    '.MaterialUnit "Geometry", "mm"\n', ...
    '.MaterialUnit "Time", "ns"\n', ...
    '.MaterialUnit "Temperature", "Kelvin"\n', ...
    '.Epsilon "%.4f"\n',...        %插入介电常数
    '.Mu "%.4f"\n',...             %插入磁导率
    '.Sigma "0"\n',...
    '.TanD "%.6f"\n'...             %损耗角
    '.TanDFreq "%.4f"\n',...          %损耗角的频率
    '.TanDGiven "True"\n',...
    '.TanDModel "ConstTanD"\n',...
    '.SetConstTanDStrategyEps "AutomaticOrder"\n',...
    '.ConstTanDModelOrderEps "3"\n',...
    '.DjordjevicSarkarUpperFreqEps "0"\n',...
    '.SetElParametricConductivity "False"\n',...
    '.ReferenceCoordSystem "Global"\n',...
    '.CoordSystemType "Cartesian"\n',...
    '.SigmaM "0"\n',...
    '.TanDM "0.0"\n',...
    '.TanDMFreq "0.0"\n',...
    '.TanDMGiven "False"\n',...
    '.TanDMModel "ConstTanD"\n',...
    '.SetConstTanDStrategyMu "AutomaticOrder"\n',...
    '.ConstTanDModelOrderMu "3"\n',...
    '.DjordjevicSarkarUpperFreqMu "0"\n',...
    '.SetMagParametricConductivity "False"\n',...
    '.DispModelEps "None"\n',...
    '.DispModelMu "None"\n',...
    '.DispersiveFittingSchemeEps "Nth Order"\n',...
    '.MaximalOrderNthModelFitEps "10"\n',...
    '.ErrorLimitNthModelFitEps "0.1"\n',...
    '.UseOnlyDataInSimFreqRangeNthModelEps "False"\n',...
    '.DispersiveFittingSchemeMu "Nth Order"\n',...
    '.MaximalOrderNthModelFitMu "10"\n',...
    '.ErrorLimitNthModelFitMu "0.1"\n',...
    '.UseOnlyDataInSimFreqRangeNthModelMu "False"\n',...
    '.UseGeneralDispersionEps "False"\n',...
    '.UseGeneralDispersionMu "False"\n',...
    '.NLAnisotropy "False"\n',...
    '.NLAStackingFactor "1"\n',...
    '.NLADirectionX "1"\n',...
    '.NLADirectionY "0"\n',...
    '.NLADirectionZ "0"\n',...
    '.Colour "0", "1", "1"\n',...
    '.Wireframe "False" \n',...
    '.Reflection "False" \n',...
    '.Allowoutline "True" \n',...
    '.Transparentoutline "False" \n',...
    '.Transparency "%d" \n',...         %透明度
    '.Create\n',...
    'End With'], name,epsr,mur,tand,tandfreq,transparent); % 结尾传入变量

invoke(mws,'AddToHistory',sprintf('new material:%s',name),sComment);
end

