function scommend_out = defineBrick_VBAOnly(mws,command,objName,componentName,centerPoint,xSize,ySize,zSize,material)
%DEFINEBRICK 新建一个长方体

% 坐标处理
xrange = [centerPoint(1)-xSize/2, centerPoint(1)+xSize/2];
yrange = [centerPoint(2)-ySize/2, centerPoint(2)+ySize/2];
zrange = [centerPoint(3)-zSize/2, centerPoint(3)+zSize/2];

% 名称处理
objName = ensure_cst_string(objName);
componentName = ensure_cst_string(componentName);

if ~check_material_exists(mws,material)
    error('材料 %s 不存在，先去新建材料',material);
end

scomment = sprintf([...
    'With Brick\n', ...
    '.Reset\n', ...
    '.Name "%s"\n', ...
    '.Component "%s"\n', ...
    '.Material "%s"\n', ...
    '.Xrange "%.4f", "%.4f"\n', ...
    '.Yrange "%.4f", "%.4f"\n', ...
    '.Zrange "%.4f", "%.4f"\n', ...
    '.Create\n', ...
    'End With'], ...  % <--- 注意这里！字符串数组在这里结束
    objName, componentName, material, ... % 变量作为 sprintf 的后续参数传入
    xrange(1), xrange(2), ...
    yrange(1), yrange(2), ...
    zrange(1), zrange(2));

scommend_out = [command 10 scomment];
end

