function defineBrick(mws,objName,componentName,centerPoint,xSize,ySize,zSize,material)
%DEFINEBRICK 新建一个长方体

% 坐标处理
xrange = [centerPoint(1)-xSize/2, centerPoint(1)+xSize/2];
yrange = [centerPoint(2)-ySize/2, centerPoint(2)+ySize/2];
zrange = [centerPoint(3)-zSize/2, centerPoint(3)+zSize/2];

% 名称处理
objName = ensure_cst_string(objName);
componentName = ensure_cst_string(componentName);

if ~check_material_exists(mws,material)
    error('材料 %s 不存在，先去新建材料',material);
end

% scomment = sprintf([...
%     'With Brick\n',...
%     '.Reset\n',...
%     '.Name "%s"\n',...
%     '.Component "%s"\n',...
%     '.Material "%s"\n',...
%     '.Xrange "%.4f", "%.4f"\n',...
%     '.Yrange "%.4f", "%.4f"\n',...
%     '.Zrange "%.4f", "%.4f"\n',...
%     '.Create\n'
%     'End With'],...
%     objName,componentName,material,...
%     xrange(1),xrange(2),...
%     yrange(1),yrange(2),...
%     zrange(1),zrange(2));

% 使用 sprintf 构建 VBA 指令
% 注意1：所有的 \n 都是必须的，CST 需要换行符来区分指令
% 注意2：方括号 ] 必须在格式字符串结束后立刻闭合
scomment = sprintf([...
    'With Brick\n', ...
    '.Reset\n', ...
    '.Name "%s"\n', ...
    '.Component "%s"\n', ...
    '.Material "%s"\n', ...
    '.Xrange "%.4f", "%.4f"\n', ...
    '.Yrange "%.4f", "%.4f"\n', ...
    '.Zrange "%.4f", "%.4f"\n', ...
    '.Create\n', ...
    'End With'], ...  % <--- 注意这里！字符串数组在这里结束
    objName, componentName, material, ... % 变量作为 sprintf 的后续参数传入
    xrange(1), xrange(2), ...
    yrange(1), yrange(2), ...
    zrange(1), zrange(2));

% 调试建议：先打印出来看看是否符合 VBA 格式
%disp(scomment);

invoke(mws,'AddToHistory',sprintf('new brick:%s %s',objName,componentName),scomment);
end

