function setUnitBoundary(mws)
    % mws: CST 对象句柄
    % 说明：X, Y 为 Unit Cell; Z 为 Open (不自动加空间)
    
    vba_code = [...
        'With Boundary \n', ...
        ' .Xmin "unit cell" \n', ...
        ' .Xmax "unit cell" \n', ...
        ' .Ymin "unit cell" \n', ...
        ' .Ymax "unit cell" \n', ...
        ' .Zmin "open" \n', ...        % 修正点：改为 open
        ' .Zmax "open" \n', ...        % 修正点：改为 open
        ' .Xsymmetry "none" \n', ...
        ' .Ysymmetry "none" \n', ...
        ' .Zsymmetry "none" \n', ...
        ' .XPeriodicShift "0.0" \n', ...
        ' .YPeriodicShift "0.0" \n', ...
        ' .ZPeriodicShift "0.0" \n', ...
        ' .PeriodicUseConstantAngles "False" \n', ...
         ...% 注意：这里假设你已经在外部定义了 theta/phi，如果没有定义会报错
        ' .SetPeriodicBoundaryAngles "theta", "phi" \n', ... 
        ' .SetPeriodicBoundaryAnglesDirection "inward" \n', ...
        ' .UnitCellFitToBoundingBox "True" \n', ...
        ' .UnitCellDs1 "0.0" \n', ...
        ' .UnitCellDs2 "0.0" \n', ...
        ' .UnitCellAngle "90.0" \n', ...
        'End With'];

    mws.invoke('AddToHistory', 'Set Boundary Unit', vba_code);
end