from __future__ import annotations
from typing import Any


ARGS_TEMPLATES: dict[str, dict[str, Any]] = {
    "init-workspace": {
        "workspace": "C:\\path\\to\\empty_workspace",
    },
    "init-task": {
        "workspace": "C:\\path\\to\\empty_workspace",
        "task_id": "task_001_demo",
        "source_project": "C:\\path\\to\\model.cst",
        "goal": "demo",
        "title": "",
        "force": False,
    },
    "prepare-run": {
        "task_path": "C:\\path\\to\\tasks\\task_xxx",
    },
    "get-run-context": {
        "task_path": "C:\\path\\to\\tasks\\task_xxx",
        "run_id": "",
    },
    "record-stage": {
        "task_path": "C:\\path\\to\\tasks\\task_xxx",
        "run_id": "run_001",
        "stage": "cli_runtime_iteration",
        "status": "completed",
        "message": "",
        "details_json": "{}",
    },
    "update-status": {
        "task_path": "C:\\path\\to\\tasks\\task_xxx",
        "run_id": "run_001",
        "status": "validated",
        "stage": "cli_runtime_iteration",
        "best_result_json": "{}",
        "output_files_json": "{}",
        "error_json": "",
        "extra_json": "{}",
    },
    "cleanup-cst-processes": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "dry_run": False,
        "settle_seconds": 0.5,
    },
    "inspect-cst-environment": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "cst-session-inspect": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "cst-session-open": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "cst-session-reattach": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "cst-session-close": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "save": False,
        "wait_unlock": True,
        "timeout_seconds": 30,
        "poll_interval_seconds": 0.5,
    },
    "cst-session-quit": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "dry_run": False,
        "settle_seconds": 0.5,
    },
    "save-project": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "list-parameters": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "list-entities": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "component": "",
    },
    "change-parameter": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "R",
        "value": 0.102,
    },
    "start-simulation": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "start-simulation-async": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "is-simulation-running": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "wait-simulation": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "timeout_seconds": 3600,
        "poll_interval_seconds": 10,
    },
    "infer-run-dir": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "wait-project-unlocked": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "timeout_seconds": 30,
        "poll_interval_seconds": 0.5,
    },
    "list-open-projects": {},
    "verify-project-identity": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "open-results-project": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "allow_interactive": False,
        "subproject_treepath": "",
    },
    "list-subprojects": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "allow_interactive": False,
    },
    "get-version-info": {},
    "list-result-items": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "module_type": "3d",
        "filter_type": "0D/1D",
        "allow_interactive": False,
        "subproject_treepath": "",
    },
    "list-run-ids": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "treepath": "1D Results\\S-Parameters\\S1,1",
        "module_type": "3d",
        "allow_interactive": False,
        "skip_nonparametric": False,
        "max_mesh_passes_only": False,
    },
    "get-parameter-combination": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "run_id": 1,
        "module_type": "3d",
        "allow_interactive": False,
    },
    "get-1d-result": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "treepath": "1D Results\\S-Parameters\\S1,1",
        "module_type": "3d",
        "run_id": 1,
        "load_impedances": True,
        "export_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_run1.json",
        "allow_interactive": False,
    },
    "get-2d-result": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "treepath": "2D/3D Results\\example",
        "module_type": "3d",
        "export_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\result_2d.json",
        "allow_interactive": False,
        "subproject_treepath": "",
        "include_data": False,
    },
    "plot-exported-file": {
        "file_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_run1.json",
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\result_preview.html",
        "page_title": "CST Result Preview",
    },
    "plot-project-result": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "treepath": "1D Results\\S-Parameters\\S1,1",
        "module_type": "3d",
        "run_id": 1,
        "load_impedances": True,
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\project_result_preview.html",
        "page_title": "Project Result Preview",
        "allow_interactive": True,
        "subproject_treepath": "",
        "result_kind": "auto",
        "intermediate_json": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\project_result_preview.json",
    },
    "generate-s11-comparison": {
        "file_paths": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_run0.json",
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_run1.json",
        ],
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_comparison.html",
        "page_title": "S11 Comparison",
    },
    "generate-s11-farfield-dashboard": {
        "s11_file_paths": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_run1.json"
        ],
        "farfield_file_paths": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_13ghz_port1_realized_gain.txt"
        ],
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\s11_farfield_dashboard.html",
        "page_title": "S11 + Farfield Dashboard",
        "farfield_run_id": 1,
    },
    "export-run-results": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "farfield_names": [
            "farfield (f=10) [1]"
        ],
        "farfield_plot_mode": "Realized Gain",
        "farfield_theta_step": 2.0,
        "farfield_phi_step": 2.0,
    },
    "generate-report": {
        "data_dir": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001",
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\report.html",
        "page_title": "电磁仿真综合报告",
    },
    "inspect-farfield-ascii": {
        "file_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_13ghz_port1.txt",
    },
    "export-farfield-fresh-session": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "farfield_name": "farfield (f=13) [1]",
        "output_file": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_13ghz_port1_realized_gain.txt",
        "plot_mode": "Realized Gain",
        "prime_with_cut": False,
        "cut_axis": "Phi",
        "cut_angle": "0",
        "theta_step_deg": 1.0,
        "phi_step_deg": 2.0,
        "theta_min_deg": 0.0,
        "theta_max_deg": 15.0,
        "phi_min_deg": 0.0,
        "phi_max_deg": 360.0,
        "max_attempts": 6,
        "keep_prime_cut_file": False,
    },
    "export-existing-farfield-cut-fresh-session": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "tree_path": "Farfields\\Farfield Cuts\\Excitation [1]\\Phi=0\\farfield (f=13)",
        "output_file": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_cut_phi0_port1.txt",
    },
    "read-realized-gain-grid-fresh-session": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "farfield_name": "farfield (f=13) [1]",
        "run_id": "",
        "theta_step_deg": 1.0,
        "phi_step_deg": 2.0,
        "theta_min_deg": 0.0,
        "theta_max_deg": 15.0,
        "phi_min_deg": 0.0,
        "phi_max_deg": 360.0,
        "selection_tree_path": "1D Results\\S-Parameters",
        "output_json": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\realized_gain_grid.json",
    },
    "calculate-farfield-neighborhood-flatness": {
        "file_paths": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\farfield_cut_phi0_port1.json",
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\farfield_cut_phi90_port1.json",
        ],
        "theta_max_deg": 15.0,
        "output_json": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\farfield_flatness.json",
    },
    "plot-farfield-multi": {
        "file_paths": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_13ghz_port1_realized_gain.txt"
        ],
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\exports\\farfield_preview.html",
        "page_title": "Farfield Preview",
    },
    "define-brick": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "my_brick",
        "component": "Component1",
        "material": "PEC",
        "x_min": -10,
        "x_max": 10,
        "y_min": -10,
        "y_max": 10,
        "z_min": 0,
        "z_max": 20,
    },
    "define-cylinder": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "my_cylinder",
        "component": "Component1",
        "material": "PEC",
        "outer_radius": 5,
        "inner_radius": 0,
        "axis": "z",
        "z_min": 0,
        "z_max": 20,
        "x_center": 0,
        "y_center": 0,
    },
    "define-cone": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "my_cone",
        "component": "Component1",
        "material": "PEC",
        "bottom_radius": 5,
        "top_radius": 15,
        "axis": "z",
        "z_min": 0,
        "z_max": 30,
        "x_center": 0,
        "y_center": 0,
    },
    "define-rectangle": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "my_rect",
        "curve": "curve1",
        "x_min": -10,
        "x_max": 10,
        "y_min": -5,
        "y_max": 5,
    },
    "boolean-subtract": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "target": "Component1:outer",
        "tool": "Component1:inner",
    },
    "boolean-add": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape1": "Component1:part1",
        "shape2": "Component1:part2",
    },
    "boolean-intersect": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape1": "Component1:part1",
        "shape2": "Component1:part2",
    },
    "boolean-insert": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape1": "Component1:outer",
        "shape2": "Component1:insert",
    },
    "delete-entity": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "component": "Component1",
        "name": "temp_shape",
    },
    "create-component": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "component_name": "MyComponent",
    },
    "change-material": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape_name": "Component1:my_brick",
        "material": "Copper (pure)",
    },
    "define-frequency-range": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "start_freq": 2.0,
        "end_freq": 18.0,
    },
    "change-frequency-range": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "min_frequency": "2",
        "max_frequency": "18",
    },
    "change-solver-type": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "solver_type": "HF Time Domain",
    },
    "define-background": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "define-boundary": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "define-mesh": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "steps_per_wave_near": 5,
        "steps_per_wave_far": 5,
        "steps_per_box_near": 5,
        "steps_per_box_far": 1,
    },
    "define-solver": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "stimulation_port": "All",
        "steady_state_limit": -40,
        "norming_impedance": 50,
    },
    "define-port": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "port_number": "1",
        "x_min": -10,
        "x_max": 10,
        "y_min": -10,
        "y_max": 10,
        "z_min": 0,
        "z_max": 5,
        "orientation": "zmin",
    },
    "define-monitor": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "start_freq": 2.0,
        "end_freq": 18.0,
        "step": 1,
    },
    "rename-entity": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "old_name": "Component1:old_name",
        "new_name": "Component1:new_name",
    },
    "set-entity-color": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape_name": "Component1:my_brick",
        "r": 255,
        "g": 0,
        "b": 0,
    },
    "list-materials": {},
    "stop-simulation": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "pause-simulation": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "resume-simulation": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "define-units": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "length": "mm",
        "frequency": "GHz",
    },
    "set-farfield-monitor": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "start_freq": 2.0,
        "end_freq": 18.0,
        "step": 1,
    },
    "create-blank-project": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "set-efield-monitor": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "start_freq": 2.0,
        "end_freq": 18.0,
        "step": 1,
    },
    "set-field-monitor": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "field_type": "H",
        "start_frequency": "2",
        "end_frequency": "18",
        "num_samples": "10",
    },
    "set-probe": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "field_type": "E",
        "x_pos": "0",
        "y_pos": "0",
        "z_pos": "5",
    },
    "delete-probe": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "probe_id": "1",
    },
    "delete-monitor": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "monitor_name": "farfield (f=10)",
    },
    "set-background-with-space": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "set-farfield-plot-cuts": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "show-bounding-box": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "activate-post-process": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "operation": "envelop",
        "enable": True,
    },
    "create-mesh-group": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "group_name": "fine_mesh",
        "items": ["solid1", "solid2"],
    },
    "set-solver-acceleration": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "use_parallelization": True,
        "max_threads": 1024,
    },
    "set-fdsolver-extrude-open-bc": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "set-mesh-fpbavoid-nonreg-unite": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "set-mesh-minimum-step-number": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "num_steps": 5,
    },
    "define-polygon-3d": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "my_polygon",
        "curve": "curve1",
        "points": [["-10", "0", "0"], ["10", "0", "0"], ["10", "0", "10"], ["-10", "0", "10"], ["-10", "0", "0"]],
    },
    "define-analytical-curve": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "exp_curve",
        "curve": "curve1",
        "law_x": "C1*exp(R*t)+C2",
        "law_y": "0",
        "law_z": "t",
        "param_start": "0",
        "param_end": "10",
    },
    "define-extrude-curve": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "extruded_part",
        "component": "Component1",
        "material": "PEC",
        "curve": "curve1:my_polygon",
        "thickness": 5,
    },
    "transform-shape": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "shape_name": "Component1:my_shape",
        "transform_type": "mirror",
        "center_x": "0",
        "center_y": "0",
        "center_z": "0",
        "plane_normal_x": "0",
        "plane_normal_y": "1",
        "plane_normal_z": "0",
    },
    "transform-curve": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "curve_name": "curve1:my_curve",
        "center_x": "0",
        "center_y": "0",
        "center_z": "0",
        "plane_normal_x": "0",
        "plane_normal_y": "1",
        "plane_normal_z": "0",
    },
    "create-horn-segment": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "segment_id": 1,
        "bottom_radius": 8,
        "top_radius": 25,
        "z_min": 0,
        "z_max": 30,
    },
    "create-loft-sweep": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "horn_shell",
        "component": "HornAntenna",
        "material": "PEC",
        "x_min1": -10, "x_max1": 10, "y_min1": -10, "y_max1": 10, "z1": 0,
        "x_min2": -35, "x_max2": 35, "y_min2": -35, "y_max2": 35, "z2": 50,
    },
    "create-hollow-sweep": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "horn",
        "component": "HornAntenna",
        "material": "PEC",
        "x_min1": -10, "x_max1": 10, "y_min1": -10, "y_max1": 10, "z1": 0,
        "x_min2": -35, "x_max2": 35, "y_min2": -35, "y_max2": 35, "z2": 50,
        "wall_thickness": 2.0,
    },
    "add-to-history": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "command": 'Solid.Add "Component1:solid1", "Component1:solid2"',
        "history_name": "custom boolean add",
    },
    "pick-face": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "component": "Component1",
        "name": "profile_wall",
        "face_id": "1",
    },
    "define-loft": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "name": "loft_result",
        "component": "Component1",
        "material": "PEC",
        "tangency": 0,
        "minimize_twist": True,
    },
    "export-e-field": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "frequency": "10",
        "file_path": "C:\\path\\to\\run\\exports",
    },
    "export-surface-current": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "frequency": "10",
        "file_path": "C:\\path\\to\\run\\exports",
    },
    "export-voltage": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "voltage_index": "0",
        "file_path": "C:\\path\\to\\run\\exports",
    },
    "define-parameters": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "names": ["a", "b", "h"],
        "values": ["10", "5*b", "2"],
    },
    "define-material-from-mtd": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "material_name": "Copper (pure)",
    },
    "install-cst-libraries": {
        "cst_path": "C:\\Program Files\\CST Studio Suite 2026\\AMD64\\python_cst_libraries",
        "dry_run": True,
    },
    "health-check": {
        "workspace": "",
        "auto_fix": True,
    },
    "stage-evidence": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "capture": ["parameters", "entities", "file_info"],
        "stage_name": "snapshot_before_modeling",
        "output_dir": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis",
        "compare": [
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\snapshot_before.json",
            "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\snapshot_after.json"
        ],
        "output_html": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\analysis\\evidence_report.html",
    },
    "inspect-project": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
    },
    "prepare-experiment": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "param_name": "g",
        "param_value": 23.5,
    },
    "run-experiment": {
        "project_path": "C:\\path\\to\\tasks\\task_xxx\\runs\\run_001\\projects\\working.cst",
        "farfield_names": [],
        "farfield_plot_mode": "Realized Gain",
        "farfield_theta_step": 2.0,
        "farfield_phi_step": 2.0,
        "timeout_seconds": 3600,
    },
}
